// <auto-generated />
using System;
using Cristalyn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cristalyn.Migrations.Cristalyn
{
    [DbContext(typeof(CristalynContext))]
    [Migration("20250617193442_UpdateCristalynContext")]
    partial class UpdateCristalynContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cristalyn.Models.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CuponId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailUtilizator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Reducere")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CuponId");

                    b.ToTable("Comenzi");
                });

            modelBuilder.Entity("Cristalyn.Models.CosItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantitate")
                        .HasColumnType("int");

                    b.Property<int?>("ComandaId")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.ToTable("CosItem");
                });

            modelBuilder.Entity("Cristalyn.Models.Cupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("EsteProcentual")
                        .HasColumnType("bit");

                    b.Property<int?>("NumarMaximUtilizari")
                        .HasColumnType("int");

                    b.Property<int>("UtilizariCurente")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidDeLa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidPanaLa")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Valoare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValoareMinimaComanda")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Cupoane");
                });

            modelBuilder.Entity("Cristalyn.Models.Produs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImagineUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Produse");
                });

            modelBuilder.Entity("Cristalyn.Models.PuncteFidelitate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailUtilizator")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PuncteAcumulate")
                        .HasColumnType("int");

                    b.Property<int>("PuncteFolosite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmailUtilizator")
                        .IsUnique();

                    b.ToTable("PuncteFidelitate");
                });

            modelBuilder.Entity("Cristalyn.Models.ReducereCategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descriere")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProcentReducere")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidDeLa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidPanaLa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Categorie");

                    b.ToTable("ReduceriCategorii");
                });

            modelBuilder.Entity("Cristalyn.Models.Utilizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilizatori");
                });

            modelBuilder.Entity("Cristalyn.Models.Comanda", b =>
                {
                    b.HasOne("Cristalyn.Models.Cupon", "Cupon")
                        .WithMany()
                        .HasForeignKey("CuponId");

                    b.Navigation("Cupon");
                });

            modelBuilder.Entity("Cristalyn.Models.CosItem", b =>
                {
                    b.HasOne("Cristalyn.Models.Comanda", null)
                        .WithMany("Produse")
                        .HasForeignKey("ComandaId");
                });

            modelBuilder.Entity("Cristalyn.Models.Comanda", b =>
                {
                    b.Navigation("Produse");
                });
#pragma warning restore 612, 618
        }
    }
}
